name: Setup devenv

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@master
      with:
        load_nixConfig: false

    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v3
      with:
        key: cache-${{ matrix.os }}-${{ hashFiles('**/*.nix') }}
        restore-keys: |
          cache-${{ matrix.os }}-

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: Install devenv.sh
      shell: bash
      run: nix profile install tarball+https://install.devenv.sh/python-rewrite

    - name: Build the devenv shell
      shell: bash
      run: devenv ci
