name: Setup devenv

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v23

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: devenv

    - name: Install devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest
      shell: bash

    - name: Build the devenv shell
      run: devenv ci
      shell: bash
