name: Setup environment variables

runs:
  using: "composite"
  steps:
    # TODO: use devenv or npm or cache the binary
    - name: Install Infisical CLI
      shell: bash
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
        sudo apt-get update && sudo apt-get install -y infisical

    - name: Pull .env files
      shell: bash
      run: pnpm env:pull
