name: Setup Nix

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v26

    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v4
      with:
        key: cache-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
        restore-keys: |
          cache-${{ runner.os }}-nix-store-

    - name: Create a custom shell for devenv
      shell: bash
      run: |
        sudo echo "#\!/usr/bin/env bash" > /usr/bin/devenv
        sudo echo "nix develop --impure --command bash -c \"\$@\"" >> /usr/bin/devenv
        sudo chmod +x /usr/bin/devenv

    - name: Build the devenv shell
      shell: devenv
      run: echo 🚀