name: Setup Playwright

runs:
  using: "composite"
  steps:
    - name: Store Playwright's Version
      shell: devenv {0}
      run: |
        PLAYWRIGHT_VERSION=$(pnpm ls --recursive @playwright/test --json | jq --raw-output 'first(.[] | select(.devDependencies["@playwright/test"]? != null) | .devDependencies["@playwright/test"].version)')
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      shell: devenv {0}
      run: pnpm dlx playwright@${{ env.PLAYWRIGHT_VERSION }} install --with-deps

    - name: Setup Playwright environment variables
      shell: devenv {0}
      run: echo "PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=true" >> $GITHUB_ENV
