name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: devenv {0}

env:
  INFISICAL_ENV: ${{ vars.INFISICAL_ENV }}
  INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  test-type-check:
    if: github.event.pull_request.draft == false
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Type check
        run: pnpm type-check

  test-lint:
    if: github.event.pull_request.draft == false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

  test-lint-monorepo:
    if: github.event.pull_request.draft == false
    name: Lint monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint monorepo
        run: pnpm lint-monorepo

  test-unit-integration:
    if: github.event.pull_request.draft == false
    name: Unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit and integration tests
        run: pnpm test

  test-components:
    if: github.event.pull_request.draft == false
    name: Component tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          playwright: true

      - name: Run components tests
        run: pnpm test:components

  test-storybook:
    if: github.event.pull_request.draft == false
    name: Storybook tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          playwright: true

      - name: Run Storybook tests
        run: pnpm test:storybook

  test-e2e:
    if: github.event.pull_request.draft == false
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          playwright: true

      - name: Run E2E tests
        run: pnpm test:e2e