name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: devenv shell bash -e {0}

env:
  INFISICAL_ENV: ${{ vars.INFISICAL_ENV }}
  INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  test-type-check:
    if: github.event.pull_request.draft == false
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v23

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install devenv.sh
        shell: bash
        run: nix profile install tarball+https://install.devenv.sh/python-rewrite

      - name: Build the devenv shell
        shell: bash
        run: devenv ci

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Setup environment variables
        uses: ./.github/actions/setup-env

      - name: Type check
        run: pnpm type-check

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3

  test-lint:
    if: github.event.pull_request.draft == false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3

  test-lint-monorepo:
    if: github.event.pull_request.draft == false
    name: Lint monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint monorepo
        run: pnpm lint-monorepo

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3

  test-unit-integration:
    if: github.event.pull_request.draft == false
    name: Unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit and integration tests
        run: pnpm test

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3

  test-components:
    if: github.event.pull_request.draft == false
    name: Component tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run components tests
        run: pnpm test:components

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3

  test-storybook:
    if: github.event.pull_request.draft == false
    name: Storybook tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Storybook tests
        run: pnpm test:storybook

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3

  test-e2e:
    if: github.event.pull_request.draft == false
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run E2E tests
        run: pnpm test:e2e

      # - if: ${{ failure() }}
      #   uses: andymckay/cancel-action@0.3
