name: Tests

on:
  pull_request:
    types: [ready_for_review, opened, synchronize]
    branches:
      - main

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  test-type-check:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Type check
        run: pnpm type-check

      - if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  test-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Lint
        run: pnpm lint

      - if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  test-unit-integration:
    name: Unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run unit and integration tests
        run: pnpm test

      - if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  test-components:
    name: Component tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run components tests
        run: pnpm test:components

      - if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  test-storybook:
    name: Storybook tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run Storybook tests
        run: pnpm test:storybook

      - if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3

  test-e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/actions/install

      - name: Run E2E tests
        run: pnpm test:e2e

      - if: ${{ failure() }}
        uses: andymckay/cancel-action@0.3
