name: Tests

on:
  push:
    branches:
      - main

concurrency:
  group: update-cache
  cancel-in-progress: true

jobs:
  update-cache:
    name: Update cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
