name: Update cache

on:
  push:
    branches:
      - main

concurrency:
  group: update-cache
  cancel-in-progress: true

env:
  INFISICAL_ENV: ${{ vars.INFISICAL_ENV }}
  INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}

jobs:
  update-cache:
    name: Update cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          playwright: true
